language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - libdrm-dev
git:
    depth: 3
script:
    - ./autogen.sh
    - ./DO_CONF
    - make && make install
sudo: required
dist: trusty
before_install:
    - sudo apt-get update
    - sudo apt-get upgrade -y
