#!/bin/bash

PARAM=""

PARAM="$PARAM --enable-jpeg"
PARAM="$PARAM --enable-drm"
PARAM="$PARAM --enable-drm-basic"
PARAM="$PARAM --enable-drm-radeon"
PARAM="$PARAM --enable-drm-intel"
PARAM="$PARAM --enable-drm-i915"
#PARAM="$PARAM --enable-drm-i965"
PARAM="$PARAM --enable-png"
PARAM="$PARAM --enable-gallium"

./autogen.sh \
    --prefix=/home/nekrad/.usr/cairo \
    --disable-xlib \
    --enable-xcb \
    --disable-ps \
    --disable-pdf \
    --disable-interpreter \
    --disable-gobject \
    --disable-svg \
    --with-gallium=$HOME/src/packaging/pkg/mesa.git \
    $PARAM
